sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: YOUR_KEY_ID
    access-key-secret: YOUR_KEY_SECRET
    bucket-name: web-sky-takeout-devin
